name: Publish to Packagist on Release

on:
  release:
    types: [published]

jobs:
  packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Packagist about new release
        run: |
          curl -X POST https://packagist.org/api/update-package \
          -H 'Accept: application/json' \
          -d "username=${{ secrets.PACKAGIST_USERNAME }}" \
          -d "apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
          -d "repository=https://github.com/${{ github.repository }}.git"

